const $=id=>document.getElementById(id);
let manifest,index=0,file=null,worker=null,url=null,busy=false;const completed=new Set();
const tabs=[...document.querySelectorAll('[role=tab]')];
const bytes=n=>`${(n/1e6).toFixed(1)} MB`;
function status(text,kind=''){$('status').textContent=text;$('status').className=`status ${kind}`;}
function discard(){if(url)URL.revokeObjectURL(url);url=null;$('download').hidden=true;$('save-tip').hidden=true;$('start').hidden=false;}
function setBusy(value){busy=value;$('game-file').disabled=value;tabs.forEach(t=>t.disabled=value);$('start').disabled=value||!file;$('cancel').hidden=!value;$('dropzone').classList.toggle('busy',value);}
function select(i){if(busy||!manifest)return;index=i;file=null;discard();$('game-file').value='';$('chosen-name').textContent='เลือกไฟล์ต้นฉบับ';$('chosen-detail').textContent='แตะเพื่อเลือกไฟล์ หรือลากไฟล์มาวางที่นี่';$('progress-row').hidden=true;const entry=manifest.files[i];$('file-title').textContent=i?'ไฟล์อัปเดตเกม':'ไฟล์เกมหลัก';$('expected').textContent=`${entry.name} · ต้นฉบับ ${bytes(entry.sourceSize)}`;$('file-panel').setAttribute('aria-labelledby',tabs[i].id);tabs.forEach((t,j)=>{t.setAttribute('aria-selected',String(j===i));t.tabIndex=j===i?0:-1;});setBusy(false);status(completed.has(i)?'สร้างไฟล์นี้สำเร็จแล้ว เลือกไฟล์ใหม่ได้หากต้องการทำซ้ำ':'พร้อมรับไฟล์ต้นฉบับ');}
function choose(f){if(busy||!manifest||!f)return;discard();file=f;$('chosen-name').textContent=f.name;$('chosen-detail').textContent=`${bytes(f.size)} · เลือกไฟล์อื่นได้โดยแตะอีกครั้ง`;$('progress-row').hidden=true;setBusy(false);status('พร้อมตรวจไฟล์ โดยไม่แก้ไขไฟล์ต้นฉบับ');}
tabs.forEach((t,i)=>{t.onclick=()=>select(i);t.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?1:1-index;select(next);tabs[next].focus();}};});
$('game-file').onchange=e=>choose(e.target.files[0]);
for(const type of ['dragenter','dragover'])$('dropzone').addEventListener(type,e=>{e.preventDefault();if(!busy)$('dropzone').classList.add('dragging');});
for(const type of ['dragleave','drop'])$('dropzone').addEventListener(type,e=>{e.preventDefault();$('dropzone').classList.remove('dragging');if(type==='drop'){if(e.dataTransfer.files.length!==1)status('กรุณาเลือกทีละหนึ่งไฟล์','error');else choose(e.dataTransfer.files[0]);}});
function fail(message){worker?.terminate();worker=null;setBusy(false);status(message,'error');}
$('start').onclick=()=>{if(!file||busy)return;discard();setBusy(true);$('progress-row').hidden=false;$('progress').value=0;$('percent').textContent='0%';$('phase').textContent='เริ่มตรวจไฟล์';status('เปิดแท็บนี้ไว้จนเสร็จ ไฟล์เกมจะไม่ถูกส่งออกจากเครื่อง');try{worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});worker.onerror=()=>fail('เครื่องมือหยุดทำงาน ลองเปิดเว็บใหม่หรือใช้คอมพิวเตอร์');worker.onmessage=({data})=>{if(data.type==='progress'){$('phase').textContent=data.phase;$('progress').value=data.percent;$('percent').textContent=`${data.percent}%`;}else if(data.type==='error')fail(data.message);else if(data.type==='done'){worker.terminate();worker=null;url=URL.createObjectURL(data.output);$('download').href=url;$('download').download=data.name;$('download').hidden=false;$('start').hidden=true;$('save-tip').hidden=false;completed.add(index);setBusy(false);status(`ตรวจสอบผ่าน · ${bytes(data.output.size)} พร้อมดาวน์โหลด`,'success');$('download').focus();}};worker.postMessage({file,entry:manifest.files[index]});}catch{fail('เบราว์เซอร์นี้เปิดเครื่องมือไม่ได้ กรุณาใช้ Chrome หรือ Edge');}};
$('cancel').onclick=()=>{worker?.terminate();worker=null;setBusy(false);$('progress-row').hidden=true;status('ยกเลิกแล้ว ไฟล์ต้นฉบับยังเหมือนเดิม');};
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}});
try{const response=await fetch('./patches/manifest.json',{cache:'no-cache'});if(!response.ok)throw Error();manifest=await response.json();if(manifest.schema!==1||manifest.files.length!==2)throw Error();if(!window.Worker||!Blob.prototype.arrayBuffer)throw Error();select(0);}catch{status('โหลดเครื่องมือไม่สำเร็จ กรุณาเปิดเว็บผ่าน HTTPS และลองโหลดหน้าใหม่','error');}
// Optional agent read-back; selection and file access always stay in the user's picker.
if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'get_patch_status',title:'ตรวจสถานะแพตช์',description:'อ่านสถานะการสร้างแพตช์ในหน้านี้ ไม่อ่านหรือส่งเนื้อหาไฟล์เกม',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(input&&Object.keys(input).length)throw Error('No parameters accepted');return {ready:!!manifest,busy,selectedArchive:manifest?.files[index].name,completedFiles:[...completed].map(i=>manifest.files[i].name),message:$('status').textContent};}});}catch{/* Optional API does not affect the patcher. */}}
